# Generated by Django 2.2 on 2021-04-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='UUID')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名')),
                ('os', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统')),
                ('kernel_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='内核版本')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU数量')),
                ('cpu_model', models.CharField(blank=True, max_length=16, null=True, verbose_name='CPU型号')),
                ('cabinet_info', models.CharField(blank=True, max_length=128, null=True, verbose_name='机柜信息')),
                ('ssh_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='SSH连接用IP')),
                ('ssh_port', models.IntegerField(blank=True, null=True, verbose_name='ssh连接用端口')),
                ('ssh_user', models.CharField(blank=True, max_length=32, null=True, verbose_name='SSH连接用账号')),
                ('ssh_pass', models.CharField(blank=True, max_length=32, null=True, verbose_name='SSH连接用密码')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.CreateModel(
            name='server_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='组名')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMDB.server')),
            ],
            options={
                'verbose_name_plural': '服务器组',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='网卡名')),
                ('mac', models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMDB.server')),
            ],
            options={
                'verbose_name_plural': '网卡',
            },
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=8, verbose_name='插槽')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('size', models.CharField(blank=True, max_length=16, null=True, verbose_name='容量')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='SN号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMDB.server')),
            ],
            options={
                'verbose_name_plural': '内存',
            },
        ),
    ]
