# Generated by Django 2.2 on 2021-04-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=32, verbose_name='UUID')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('size', models.CharField(blank=True, max_length=16, null=True, verbose_name='容量')),
                ('type', models.CharField(blank=True, max_length=16, null=True, verbose_name='类型')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMDB.server')),
            ],
            options={
                'verbose_name_plural': '磁盘',
            },
        ),
    ]
