# Generated by Django 2.2 on 2021-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_disk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='model',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='type',
        ),
        migrations.AddField(
            model_name='disk',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='磁盘名'),
            preserve_default=False,
        ),
    ]
