# Generated by Django 2.0.6 on 2018-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_server_list_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_list',
            name='root_pass',
            field=models.CharField(default='', max_length=64, verbose_name='root密码'),
            preserve_default=False,
        ),
    ]
