# Generated by Django 2.0.6 on 2018-07-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_server_list_root_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_list',
            name='external_ip',
            field=models.GenericIPAddressField(verbose_name='外部IP'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='os',
            field=models.CharField(max_length=16, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='root_pass',
            field=models.CharField(max_length=32, verbose_name='root密码'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='服务器名'),
        ),
    ]
