# Generated by Django 2.0 on 2019-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansiable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='operation',
            field=models.CharField(max_length=512),
        ),
    ]
