# Generated by Django 2.0 on 2019-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansiable', '0002_auto_20190528_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='operation',
            field=models.CharField(max_length=1024),
        ),
    ]
