# Generated by Django 2.0 on 2019-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansiable', '0003_auto_20190528_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='operation',
            field=models.CharField(max_length=10240),
        ),
    ]
