# Generated by Django 2.2 on 2021-03-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'verbose_name_plural': '磁盘'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': '内存'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'verbose_name_plural': '网卡'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': '服务器'},
        ),
        migrations.AlterModelOptions(
            name='server_group',
            options={'verbose_name_plural': '服务器组'},
        ),
    ]
