# Generated by Django 2.2 on 2021-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20210324_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='slot',
        ),
        migrations.AddField(
            model_name='disk',
            name='UUID',
            field=models.CharField(default=0, max_length=8, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
