# Generated by Django 2.2 on 2021-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_auto_20210402_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='UUID',
            field=models.CharField(max_length=32, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='UUID',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
