# Generated by Django 2.0.6 on 2018-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=32, verbose_name='应用')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('command', models.CharField(max_length=256, verbose_name='命令')),
                ('time', models.CharField(max_length=32, verbose_name='时间')),
                ('type', models.CharField(max_length=16, verbose_name='类型')),
            ],
        ),
    ]
