# Generated by Django 2.0.6 on 2018-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain_name_CRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_server', models.CharField(blank=True, max_length=32, verbose_name='域名')),
                ('apply_time', models.DateField(null=True, verbose_name='申请时间')),
                ('name_server_expiration_time', models.DateField(null=True, verbose_name='域名过期时间')),
                ('CRT_expiration_time', models.DateField(null=True, verbose_name='证书过期时间')),
                ('DNSPOD', models.CharField(blank=True, max_length=32, verbose_name='DNSPOD')),
                ('account', models.CharField(blank=True, max_length=32, verbose_name='账号')),
                ('comment', models.CharField(blank=True, max_length=32, verbose_name='备注')),
                ('ICP', models.CharField(blank=True, max_length=32, verbose_name='ICP备案号')),
            ],
        ),
        migrations.CreateModel(
            name='service_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=32, verbose_name='服务名')),
                ('service_id', models.CharField(blank=True, max_length=16, verbose_name='服务ID')),
                ('service_module', models.CharField(blank=True, max_length=16, verbose_name='服务模块')),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDC', models.CharField(blank=True, max_length=32, verbose_name='机房')),
                ('position', models.CharField(blank=True, max_length=32, verbose_name='机柜')),
                ('application', models.CharField(blank=True, max_length=128, verbose_name='应用')),
                ('external_IP', models.GenericIPAddressField(verbose_name='外部IP')),
                ('inner_IP_1', models.GenericIPAddressField(verbose_name='内部IP_1')),
                ('inner_IP_2', models.GenericIPAddressField(verbose_name='内部IP_2')),
                ('manage_IP', models.GenericIPAddressField(verbose_name='内部IP_2')),
                ('root_pass', models.CharField(blank=True, max_length=32, verbose_name='root密码')),
                ('ubuntu_pass', models.CharField(blank=True, max_length=32, verbose_name='ubuntu密码')),
                ('comment_1', models.CharField(blank=True, max_length=128, verbose_name='备注_1')),
                ('comment_2', models.CharField(blank=True, max_length=128, verbose_name='备注_2')),
                ('comment_3', models.CharField(blank=True, max_length=128, verbose_name='备注_3')),
                ('comment_4', models.CharField(blank=True, max_length=128, verbose_name='备注_4')),
            ],
        ),
    ]
