# Generated by Django 2.0.6 on 2018-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_info', '0002_table_ssh_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='external_IP',
            field=models.GenericIPAddressField(null=True, verbose_name='外部IP'),
        ),
        migrations.AlterField(
            model_name='table',
            name='inner_IP_1',
            field=models.GenericIPAddressField(null=True, verbose_name='内部IP_1'),
        ),
        migrations.AlterField(
            model_name='table',
            name='inner_IP_2',
            field=models.GenericIPAddressField(null=True, verbose_name='内部IP_2'),
        ),
        migrations.AlterField(
            model_name='table',
            name='manage_IP',
            field=models.GenericIPAddressField(null=True, verbose_name='内部IP_2'),
        ),
    ]
