# Generated by Django 2.0 on 2019-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_info', '0003_auto_20180724_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_1', models.CharField(blank=True, max_length=32, verbose_name='类型1')),
                ('class_2', models.CharField(blank=True, max_length=32, verbose_name='类型2')),
                ('class_3', models.CharField(blank=True, max_length=32, verbose_name='类型3')),
                ('login_ip', models.GenericIPAddressField(null=True, verbose_name='登录IP')),
                ('ssh_port', models.IntegerField(blank=True, null=True, verbose_name='ssh端口')),
                ('external_IP', models.GenericIPAddressField(null=True, verbose_name='外部IP')),
                ('inner_ip_1', models.GenericIPAddressField(null=True, verbose_name='内部IP_1')),
                ('inner_ip_2', models.GenericIPAddressField(null=True, verbose_name='内部IP_2')),
                ('root_password', models.CharField(blank=True, max_length=32, verbose_name='root密码')),
                ('ubuntu_password', models.CharField(blank=True, max_length=32, verbose_name='ubuntu密码')),
                ('db_password', models.CharField(blank=True, max_length=32, verbose_name='ubuntu密码')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='功能描述')),
                ('manage_ip', models.GenericIPAddressField(null=True, verbose_name='管理IP')),
                ('server_id', models.CharField(blank=True, max_length=64, verbose_name='服务器ID')),
                ('comment_1', models.CharField(blank=True, max_length=128, verbose_name='备注_1')),
                ('comment_2', models.CharField(blank=True, max_length=128, verbose_name='备注_2')),
                ('IDC', models.CharField(blank=True, max_length=32, verbose_name='机房')),
                ('position', models.CharField(blank=True, max_length=32, verbose_name='机柜')),
                ('owner', models.CharField(blank=True, max_length=32, verbose_name='机柜')),
            ],
        ),
    ]
