# Generated by Django 2.0 on 2019-04-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('task_desc', models.CharField(max_length=64)),
                ('task_type', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=32)),
                ('task_cmd', models.TextField(max_length=65525)),
                ('duration', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('pid', models.CharField(max_length=16)),
                ('pods_name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_run_time', models.DateTimeField()),
            ],
        ),
    ]
