# Generated by Django 2.0 on 2019-04-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='last_run_time',
            field=models.DateTimeField(null=True),
        ),
    ]
