# Generated by Django 2.0 on 2019-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0004_auto_20190426_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_desc',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=64),
        ),
    ]
