# Generated by Django 2.0 on 2019-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0006_auto_20190521_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_desc', models.CharField(max_length=128)),
                ('group_content', models.TextField(max_length=65525)),
                ('duration', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('task_now', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_run_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='single_tasks',
            name='pid',
        ),
    ]
