# Generated by Django 2.0 on 2019-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0007_auto_20190523_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_tasks',
            name='k8s_log',
            field=models.CharField(default='', max_length=128),
        ),
    ]
