# Generated by Django 2.0 on 2019-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0009_task_group_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_tasks',
            name='task_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='task_group',
            name='group_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
