# Generated by Django 2.0 on 2019-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0010_auto_20190524_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_tasks',
            name='k8s_log',
        ),
        migrations.RemoveField(
            model_name='task_group',
            name='pid',
        ),
        migrations.AddField(
            model_name='single_tasks',
            name='task_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='task_group',
            name='task_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
